[package]
name = "conn_postgres"
version = "0.1.0"
edition = "2021"

[dependencies]
common = {path = "../common"}
conn = {path = "../conn"}
postgres = "0.19.9"

[[test]]
name = "test_root"
path = "tests/mod.rs"