[package]
name = "mypip_interpreter"
version = "0.1.0"
edition = "2021"

resolver = "2"

[dependencies]
mlua = { version = "0.11", features = ["lua54", "vendored"] }
common_rs = {git = "https://github.com/DevSanso/common_rs" , package = "common_rs", tag="v0.1.2"}
mypip_types = {path = "../types"}