


[plan.plan1]
interval = {connection="", second=5}
type     = "query"
chain = [
    {connection="service", query="select $1", args =[
        { data = "hello", idx = 0}
    ]},
    {connection="data_store", query="insert into testing(num) values($1) ", bind=[
        {  idx = 0, row = 0, col = 0}
    ]},
]

[plan.plan2]
interval = {connection="service", second=5}
type     = "script"
script   = {lang="lua", file = "tseting.lua"}