


[plan.plan1]
interval = {connection="", second=5}
type     = "query"
chain = [
    {id="first", connection="service", query="select $1 as num", args =[
        { data = "hello", idx = 1}
    ]},
    {id="final", connection="data_store", query="insert into testing(num) values($1) ", bind=[
        {  id="first", key="num", col=1, idx=1 }
    ]},
]

[plan.plan2]
interval = {connection="service", second=5}
type     = "script"
script   = {lang="lua", file = "tseting.lua"}